name: run-ann-bench

on: pull_request

jobs:
  run:    
    runs-on: ubuntu-latest
    # container: docker://dvcorg/cml-py3:latest
    steps:
      # Clone this repository
      - name: Checkout this repository
        uses: actions/checkout@v2

      # Clone annbench on ./annbench
      - name: Checkout annbench
        uses: actions/checkout@v2
        with:
          repository: matsui528/annbench
          path: annbench

      # Run the benchmark
      # Note that `cml-send-comment` must be run on the original position (the root of this repo)
      - name: Run annbench
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sleep 100
          apt-get update -y
          apt-get upgrade -y
          apt-get install -y byobu
          apt-get install -y libpython3-dev



        # which python 
        # python --version
        # pip --version

        # cd annbench
        # pip install -r requirements.txt
        # python download.py dataset=siftsmall
        # python run.py dataset=siftsmall algo=annoy num_trial=1
        # python plot.py

        # cd ../
        # cat ./annbench/result_img/siftsmall.yaml  >> report.md
        # cml-publish ./annbench/result_img/siftsmall.png --md >> report.md
        # cml-send-comment report.md

          
