name: run-ann-bench

on:
  # Trigger the workflow on push,
  # but only for the "default_action" branch
  push:
    branches:
      - default_action

jobs:
  # # Run with a CML container. Easy and simple, but w/o anaconda
  # run_cml:    
  #   runs-on: ubuntu-latest
  #   container: docker://dvcorg/cml-py3:latest
  #   steps:
  #     # Clone this repository
  #     - name: Checkout this repository
  #       uses: actions/checkout@v2

  #     # Clone annbench on ./annbench
  #     - name: Checkout annbench
  #       uses: actions/checkout@v2
  #       with:
  #         repository: matsui528/annbench
  #         path: annbench

  #     # Install dependencies. Reccomend to run `apt-get update` first
  #     - name: Setup libraries
  #       run: |
  #         apt-get -y update
  #         # For pybind11
  #         apt-get -y install libpython3-dev

  #     # Run the benchmark
  #     - name: Run annbench
  #       run: |
  #         which python 
  #         python --version
  #         pip --version

  #         cd annbench
  #         pip install -r requirements.txt
  #         python download.py dataset=siftsmall
  #         python run.py --multirun dataset=siftsmall algo=annoy,hnsw,scann
  #         python plot.py
  #         cd ../

  #     # Note that `cml-send-comment` must be run on the original position (the root of this repo)
  #     - name: Publish the result by CML
  #       env:
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #       run: |
  #         echo "## Run with a cml container" >> report.md
  #         cml-publish ./annbench/result_img/siftsmall.png --md >> report.md
  #         cml-send-comment report.md


  # Run with an anaconda container. Need to install cml commands manually
  run_conda:    
    runs-on: ubuntu-latest
    container: docker://continuumio/anaconda3:latest
    steps:
      # Clone this repository
      - name: Checkout this repository
        uses: actions/checkout@v2

      # Clone annbench on ./annbench
      - name: Checkout annbench
        uses: actions/checkout@v2
        with:
          repository: matsui528/annbench
          path: annbench

      # Install Node for npm
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      # Install dependencies. Reccomend to run `apt-get update` first
      - name: Setup libraries
        run: |
          apt-get -y update
          apt-get -y install build-essential

          # Install dvc commands
          npm i -g @dvcorg/cml

      # Run the benchmark and publish the result
      # Note that `cml-send-comment` must be run on the original position (the root of this repo)
      - name: Run annbench
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          which python 
          python --version
          pip --version
          which conda
          conda --version

          cd annbench
          pip install -r requirements.txt
          conda install faiss-cpu -y -c pytorch
          python download.py dataset=siftsmall

          # Run benchmarks with several parameter combinations,
          # then output the result to report.md
          bash ../sanity_check.sh

          cd ../
          cml-send-comment report.md



