name: run-ann-bench

on:
  # Trigger the workflow on push,
  # but only for the "default_action" branch
  push:
    branches:
      - default_action

jobs:

  # # Run with a CML container. Easy and simple, but w/o anaconda
  # run_cml:    
  #   runs-on: ubuntu-latest
  #   container: docker://dvcorg/cml-py3:latest
  #   steps:
  #     # Clone this repository
  #     - name: Checkout this repository
  #       uses: actions/checkout@v2

  #     # Clone annbench on ./annbench
  #     - name: Checkout annbench
  #       uses: actions/checkout@v2
  #       with:
  #         repository: matsui528/annbench
  #         path: annbench

  #     # Run the benchmark
  #     # Note that `cml-send-comment` must be run on the original position (the root of this repo)
  #     - name: Run annbench
  #       env:
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #       run: |
  #         # To install packages in a CML conatiner, you need to run 'apt-get update' first
  #         apt-get -y update
  #         # For pybind11
  #         apt-get -y install libpython3-dev

  #         which python 
  #         python --version
  #         pip --version

  #         cd annbench
  #         pip install -r requirements.txt
  #         python download.py dataset=siftsmall
  #         python run.py --multirun dataset=siftsmall algo=annoy,hnsw
  #         python plot.py

  #         cd ../
  #         echo "## Run with a cml container" >> report.md
  #         cml-publish ./annbench/result_img/siftsmall.png --md >> report.md
  #         cml-send-comment report.md


  # Run with an anaconda container. Need to install cml commands manually
  run_conda:    
    runs-on: ubuntu-latest
    container: docker://continuumio/anaconda3:latest
    steps:
      # Clone this repository
      - name: Checkout this repository
        uses: actions/checkout@v2

      # Clone annbench on ./annbench
      - name: Checkout annbench
        uses: actions/checkout@v2
        with:
          repository: matsui528/annbench
          path: annbench

      # Install Node for npm
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup libraries
        run: |
          apt-get -y update
          apt-get -y install build-essential

          # Install dvc commands
          npm i -g @dvcorg/cml

      - name: Run annbench
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          which python 
          python --version
          pip --version
          which conda
          conda --version

          cd annbench
          pip install -r requirements.txt
          conda install faiss-cpu -y -c pytorch
          python download.py dataset=sift1m
          # python run.py --multirun dataset=sift1m algo=linear,annoy,ivfpq,hnsw
          python run.py --multirun dataset=sift1m algo=ivfpq num_trial=1
          python plot.py
          cd ../

      # Note that `cml-send-comment` must be run on the original position (the root of this repo)
      - name: Publish result by CML
        run: |
          echo "## Run with a conda container" >> report.md
          cml-publish ./annbench/result_img/sift1m.png --md >> report.md
          cml-send-comment report.md

      - name: Commit the result
        run: |  
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          DIR_NAME=`date '+%Y_%m_%d'`
          mkdir -p ./result_img/$DIR_NAME

          mv ./annbench/result_img/sift1m.png ./result_img/$DIR_NAME
          mv ./annbench/result_img/sift1m.yaml ./result_img/$DIR_NAME

          git add result_img
          git commit -m "Added artifacts from github actions" -a


      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

