name: run-ann-bench-aws

on:
  # Trigger the workflow on push,
  # but only for the "aws_action" branch
  push:
    branches:
      - aws_action

jobs:
  # Run on AWS EC2. Note that ami must be Deep Learning AMI.
  # It is because we would like to use conda without docker, otherwise we need to manually install docker
  run_aws:
    runs-on: self-hosted
    container: docker://continuumio/anaconda3:latest
    steps:
      # Clone this repository
      - name: Checkout this repository
        uses: actions/checkout@v2

      # Clone annbench on ./annbench
      - name: Checkout annbench
        uses: actions/checkout@v2
        with:
          repository: matsui528/annbench
          path: annbench

      # Install Node for npm
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      # Install dependencies
      # Note that you need "sudo" for self-hosted runner
      - name: Setup libraries
        run: |
          # sudo apt-get -y update
          # sudo apt-get -y install build-essential
          apt-get -y update
          apt-get -y install build-essential

          # Install dvc commands
          npm i -g @dvcorg/cml

      - name: Run annbench
        run: |
          which python 
          python --version
          pip --version
          which conda
          conda --version
          
          ec2metadata | grep ami-id: 
          ec2metadata | grep instance-type:

          cd annbench
          pip install -r requirements.txt
          conda install faiss-cpu -y -c pytorch
          python download.py dataset=siftsmall
          python run.py --multirun dataset=siftsmall algo=linear,annoy,ivfpq,hnsw
          python plot.py
          cd ../

      # Note that `cml-send-comment` must be run on the original position (the root of this repo)
      - name: Publish result by CML
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Run with an ec2" >> report.md
          echo "- " >> report.md
          ec2metadata | grep ami-id: >> report.md
          echo "- " >> report.md
          ec2metadata | grep instance-type: >> report.md
          cml-publish ./annbench/result_img/sift1m.png --md >> report.md
          cml-send-comment report.md

#       # - name: Commit the result
#       #   run: |  
#       #     git config --local user.email "action@github.com"
#       #     git config --local user.name "GitHub Action"
          
#       #     DIR_NAME=`date '+%Y_%m_%d'`
#       #     mkdir -p ./result_img/$DIR_NAME

#       #     mv ./annbench/result_img/sift1m.png ./result_img/$DIR_NAME
#       #     mv ./annbench/result_img/sift1m.yaml ./result_img/$DIR_NAME

#       #     git add result_img
#       #     git commit -m "Added artifacts from github actions" -a


#       # - name: Push
#       #   uses: ad-m/github-push-action@master
#       #   with:
#       #     github_token: ${{ secrets.GITHUB_TOKEN }}
#       #     branch: ${{ github.ref }}

